version: "3.8"

services:
  # 🗃 Database
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ⚙️ Backend API
  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/todoapp?schema=public
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  # 💻 Frontend (React + Vite)
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://backend:4000/api/tasks
    ports:
      - "5173:80"

volumes:
  pgdata:
